# basic options
title: Dave's Blog
author: GitHub User
email:
description:
twitter_username:
github_username:
show_excerpts: false
limit_posts: 4
header_pages:   
  - Weather.html
  - Recipes.html
  - Links.html
  - about.md

# Build settings
markdown: kramdown
theme: minima
