# basic options
title: Dave's Blog
author: GitHub User
email:
description:
twitter_username:
github_username:

header_pages:
  
  - Weather.html
  - Recipes.html
  - Links.html
  - About.md

# Build settings
markdown: kramdown
theme: minima
