# basic options
title: Dave's Blog
author: GitHub User
email: 
description: 
twitter_username: 
github_username:  

header_pages:
  - Page3.md
  - Page2.md
  - about.md

# Build settings
markdown: kramdown
theme: minima
